services:
  postgres:
    image: postgres:latest
    container_name: postgres_sgc
    environment:
      POSTGRES_URL: jdbc:postgresql://localhost:5435/sgc_postgres
      POSTGRES_DB: sgc_postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
