CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE TRANSACAO (
   id_produto UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tipo_pag VARCHAR(50) NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    quantidade INT NOT NULL,
    tipo_prod VARCHAR(50) NOT NULL,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TRANSACAOTOTAL(
    tipo_pag VARCHAR(50) NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    quantidade INT NOT NULL
);

CREATE TABLE TRANSACAODETALHADO(
    ID SERIAL PRIMARY KEY,
    tipo_pag VARCHAR(50) NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    quantidade INT NOT NULL,
    TIPOPROD VARCHAR(50) NOT NULL,
    DATA VARCHAR(50) NOT null
);
